#!/usr/bin/env python

'''
hdaps-pivot - read hdaps position and print it
'''

# Copyright: 2008-2009 Evgeni Golov <sargentd@die-welt.net>
# License: GPL-2

from hdaps import *
from time import sleep
import getopt
import sys

__version__ = "0.1"

def pivot(count=1000, verbose=False):
	calX,calY = readPosition(True)
	print '(x,y) base: (%u,%u)' % (calX, calY)
	for i in range(0,count):
		posX,posY = readPosition()
		print '(x,y) position: (%i,%i)' % (posX-calX, posY-calY)
		if verbose:
			print 'keyboard=%i mouse=%i' % (readKeyboardActivity(), readMouseActivity())
		sleep(0.25)

def usage():
	print 'hdaps-pivot from pyhdaps, version %s' % __version__
	print '\nOptions:'
	print '\t-c, --count <count>\tthe count of rounds it will print'
	print '\t-v, --verbose\tprint also keyboard and mouse activity'

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:], "hc:v", ["help", "count=", "verbose"])
	except getopt.GetoptError, err:
		print str(err)
		usage()
		sys.exit(2)
	verbose = False
	count = 1000
	for o, a in opts:
		if o in ("-v", "--verbose"):
			verbose = True
		elif o in ("-h", "--help"):
			usage()
			sys.exit()
		elif o in ("-c", "--count"):
			count = int(a)

	pivot(count, verbose)

if __name__ == '__main__':
	main()
